2021-10-14 18:55:28,378 django.utils.autoreload INFO     Watching for file changes with StatReloader
2021-10-14 18:55:35,863 django.request ERROR    Internal Server Error: /api/v1/news/
Traceback (most recent call last):
  File "/home/azamat/.var/app/com.jetbrains.PyCharm-Community/data/python/lib/python3.9/site-packages/django/core/handlers/exception.py", line 47, in inner
    response = get_response(request)
  File "/home/azamat/.var/app/com.jetbrains.PyCharm-Community/data/python/lib/python3.9/site-packages/django/core/handlers/base.py", line 181, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/home/azamat/.var/app/com.jetbrains.PyCharm-Community/data/python/lib/python3.9/site-packages/django/views/decorators/csrf.py", line 54, in wrapped_view
    return view_func(*args, **kwargs)
  File "/home/azamat/.var/app/com.jetbrains.PyCharm-Community/data/python/lib/python3.9/site-packages/django/views/generic/base.py", line 70, in view
    return self.dispatch(request, *args, **kwargs)
  File "/home/azamat/.var/app/com.jetbrains.PyCharm-Community/data/python/lib/python3.9/site-packages/rest_framework/views.py", line 509, in dispatch
    response = self.handle_exception(exc)
  File "/home/azamat/.var/app/com.jetbrains.PyCharm-Community/data/python/lib/python3.9/site-packages/rest_framework/views.py", line 469, in handle_exception
    self.raise_uncaught_exception(exc)
  File "/home/azamat/.var/app/com.jetbrains.PyCharm-Community/data/python/lib/python3.9/site-packages/rest_framework/views.py", line 480, in raise_uncaught_exception
    raise exc
  File "/home/azamat/.var/app/com.jetbrains.PyCharm-Community/data/python/lib/python3.9/site-packages/rest_framework/views.py", line 506, in dispatch
    response = handler(request, *args, **kwargs)
  File "/home/azamat/Рабочий стол/Django/social/soc_api/views.py", line 76, in get
    return JsonResponse(serializer.data)
  File "/home/azamat/.var/app/com.jetbrains.PyCharm-Community/data/python/lib/python3.9/site-packages/django/http/response.py", line 596, in __init__
    raise TypeError(
TypeError: In order to allow non-dict objects to be serialized set the safe parameter to False.
2021-10-14 18:57:20,316 django.utils.autoreload INFO     /home/azamat/Рабочий стол/Django/social/social/settings.py changed, reloading.
2021-10-14 18:57:20,742 django.utils.autoreload INFO     Watching for file changes with StatReloader
2021-10-14 18:57:22,990 django.request ERROR    Internal Server Error: /api/v1/news/
Traceback (most recent call last):
  File "/home/azamat/.var/app/com.jetbrains.PyCharm-Community/data/python/lib/python3.9/site-packages/django/core/handlers/exception.py", line 47, in inner
    response = get_response(request)
  File "/home/azamat/.var/app/com.jetbrains.PyCharm-Community/data/python/lib/python3.9/site-packages/django/core/handlers/base.py", line 181, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/home/azamat/.var/app/com.jetbrains.PyCharm-Community/data/python/lib/python3.9/site-packages/django/views/decorators/csrf.py", line 54, in wrapped_view
    return view_func(*args, **kwargs)
  File "/home/azamat/.var/app/com.jetbrains.PyCharm-Community/data/python/lib/python3.9/site-packages/django/views/generic/base.py", line 70, in view
    return self.dispatch(request, *args, **kwargs)
  File "/home/azamat/.var/app/com.jetbrains.PyCharm-Community/data/python/lib/python3.9/site-packages/rest_framework/views.py", line 509, in dispatch
    response = self.handle_exception(exc)
  File "/home/azamat/.var/app/com.jetbrains.PyCharm-Community/data/python/lib/python3.9/site-packages/rest_framework/views.py", line 469, in handle_exception
    self.raise_uncaught_exception(exc)
  File "/home/azamat/.var/app/com.jetbrains.PyCharm-Community/data/python/lib/python3.9/site-packages/rest_framework/views.py", line 480, in raise_uncaught_exception
    raise exc
  File "/home/azamat/.var/app/com.jetbrains.PyCharm-Community/data/python/lib/python3.9/site-packages/rest_framework/views.py", line 506, in dispatch
    response = handler(request, *args, **kwargs)
  File "/home/azamat/Рабочий стол/Django/social/soc_api/views.py", line 76, in get
    return JsonResponse(serializer.data)
  File "/home/azamat/.var/app/com.jetbrains.PyCharm-Community/data/python/lib/python3.9/site-packages/django/http/response.py", line 596, in __init__
    raise TypeError(
TypeError: In order to allow non-dict objects to be serialized set the safe parameter to False.
2021-10-14 18:57:23,085 django.request WARNING  Not Found: /favicon.ico
2021-10-14 18:58:20,684 django.utils.autoreload INFO     /home/azamat/Рабочий стол/Django/social/soc_api/views.py changed, reloading.
2021-10-14 18:58:21,163 django.utils.autoreload INFO     Watching for file changes with StatReloader
2021-10-14 18:58:47,193 django.utils.autoreload INFO     /home/azamat/Рабочий стол/Django/social/soc_api/views.py changed, reloading.
2021-10-14 18:58:47,594 django.utils.autoreload INFO     Watching for file changes with StatReloader
2021-10-14 19:00:11,394 django.request WARNING  Not Found: /favicon.ico
2021-10-14 19:01:02,971 django.utils.autoreload INFO     /home/azamat/Рабочий стол/Django/social/soc_api/views.py changed, reloading.
2021-10-14 19:01:03,420 django.utils.autoreload INFO     Watching for file changes with StatReloader
2021-10-14 19:01:43,970 django.request WARNING  Bad Request: /api/v1/news/
2021-10-14 19:02:06,816 django.request WARNING  Not Found: /api/v1/
2021-10-14 19:02:06,846 django.request WARNING  Not Found: /favicon.ico
2021-10-14 19:02:15,401 django.request ERROR    Internal Server Error: /api/v1/news/
Traceback (most recent call last):
  File "/home/azamat/.var/app/com.jetbrains.PyCharm-Community/data/python/lib/python3.9/site-packages/django/core/handlers/exception.py", line 47, in inner
    response = get_response(request)
  File "/home/azamat/.var/app/com.jetbrains.PyCharm-Community/data/python/lib/python3.9/site-packages/django/core/handlers/base.py", line 181, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/home/azamat/.var/app/com.jetbrains.PyCharm-Community/data/python/lib/python3.9/site-packages/django/views/decorators/csrf.py", line 54, in wrapped_view
    return view_func(*args, **kwargs)
  File "/home/azamat/.var/app/com.jetbrains.PyCharm-Community/data/python/lib/python3.9/site-packages/django/views/generic/base.py", line 70, in view
    return self.dispatch(request, *args, **kwargs)
  File "/home/azamat/.var/app/com.jetbrains.PyCharm-Community/data/python/lib/python3.9/site-packages/rest_framework/views.py", line 509, in dispatch
    response = self.handle_exception(exc)
  File "/home/azamat/.var/app/com.jetbrains.PyCharm-Community/data/python/lib/python3.9/site-packages/rest_framework/views.py", line 469, in handle_exception
    self.raise_uncaught_exception(exc)
  File "/home/azamat/.var/app/com.jetbrains.PyCharm-Community/data/python/lib/python3.9/site-packages/rest_framework/views.py", line 480, in raise_uncaught_exception
    raise exc
  File "/home/azamat/.var/app/com.jetbrains.PyCharm-Community/data/python/lib/python3.9/site-packages/rest_framework/views.py", line 506, in dispatch
    response = handler(request, *args, **kwargs)
  File "/home/azamat/Рабочий стол/Django/social/soc_api/views.py", line 76, in get
    return JsonResponse(serializer.data)
  File "/home/azamat/.var/app/com.jetbrains.PyCharm-Community/data/python/lib/python3.9/site-packages/django/http/response.py", line 596, in __init__
    raise TypeError(
TypeError: In order to allow non-dict objects to be serialized set the safe parameter to False.
2021-10-14 19:02:27,731 django.utils.autoreload INFO     /home/azamat/Рабочий стол/Django/social/soc_api/views.py changed, reloading.
2021-10-14 19:02:28,146 django.utils.autoreload INFO     Watching for file changes with StatReloader
2021-10-14 19:03:28,897 django.utils.autoreload INFO     /home/azamat/Рабочий стол/Django/social/soc_api/views.py changed, reloading.
2021-10-14 19:03:29,346 django.utils.autoreload INFO     Watching for file changes with StatReloader
2021-10-14 19:03:30,784 django.request WARNING  Not Found: /favicon.ico
2021-10-14 19:04:22,930 django.utils.autoreload INFO     /home/azamat/Рабочий стол/Django/social/soc_api/views.py changed, reloading.
2021-10-14 19:04:23,328 django.utils.autoreload INFO     Watching for file changes with StatReloader
2021-10-14 19:05:45,571 django.utils.autoreload INFO     /home/azamat/Рабочий стол/Django/social/soc_api/views.py changed, reloading.
2021-10-14 19:05:45,989 django.utils.autoreload INFO     Watching for file changes with StatReloader
2021-10-14 19:07:16,413 django.utils.autoreload INFO     /home/azamat/Рабочий стол/Django/social/soc_api/views.py changed, reloading.
2021-10-14 19:07:16,773 django.utils.autoreload INFO     Watching for file changes with StatReloader
2021-10-14 19:07:27,368 django.utils.autoreload INFO     /home/azamat/Рабочий стол/Django/social/soc_api/views.py changed, reloading.
2021-10-14 19:07:27,798 django.utils.autoreload INFO     Watching for file changes with StatReloader
2021-10-14 19:07:50,745 django.utils.autoreload INFO     /home/azamat/Рабочий стол/Django/social/soc_api/views.py changed, reloading.
2021-10-14 19:07:51,145 django.utils.autoreload INFO     Watching for file changes with StatReloader
2021-10-14 19:07:57,170 django.request WARNING  Bad Request: /api/v1/posts/
2021-10-14 19:08:18,211 django.utils.autoreload INFO     /home/azamat/Рабочий стол/Django/social/soc_api/views.py changed, reloading.
2021-10-14 19:08:18,565 django.utils.autoreload INFO     Watching for file changes with StatReloader
2021-10-14 19:08:26,920 django.request WARNING  Bad Request: /api/v1/posts/
2021-10-14 19:10:54,321 django.request ERROR    Internal Server Error: /api/v1/posts
Traceback (most recent call last):
  File "/home/azamat/.var/app/com.jetbrains.PyCharm-Community/data/python/lib/python3.9/site-packages/django/core/handlers/exception.py", line 47, in inner
    response = get_response(request)
  File "/home/azamat/.var/app/com.jetbrains.PyCharm-Community/data/python/lib/python3.9/site-packages/django/utils/deprecation.py", line 116, in __call__
    response = self.process_request(request)
  File "/home/azamat/.var/app/com.jetbrains.PyCharm-Community/data/python/lib/python3.9/site-packages/django/middleware/common.py", line 54, in process_request
    path = self.get_full_path_with_slash(request)
  File "/home/azamat/.var/app/com.jetbrains.PyCharm-Community/data/python/lib/python3.9/site-packages/django/middleware/common.py", line 88, in get_full_path_with_slash
    raise RuntimeError(
RuntimeError: You called this URL via POST, but the URL doesn't end in a slash and you have APPEND_SLASH set. Django can't redirect to the slash URL while maintaining POST data. Change your form to point to 127.0.0.1:8000/api/v1/posts/ (note the trailing slash), or set APPEND_SLASH=False in your Django settings.
2021-10-14 19:11:25,304 django.request WARNING  Bad Request: /api/v1/news/
2021-10-14 19:11:48,217 django.request WARNING  Bad Request: /api/v1/news/
2021-10-14 19:13:20,580 django.utils.autoreload INFO     /home/azamat/Рабочий стол/Django/social/soc_api/views.py changed, reloading.
2021-10-14 19:13:20,950 django.utils.autoreload INFO     Watching for file changes with StatReloader
2021-10-14 19:20:44,658 django.request WARNING  Not Found: /news/
2021-10-14 19:21:34,945 django.request WARNING  Not Found: /news/
2021-10-14 19:22:06,426 django.request WARNING  Not Found: /news/
2021-10-14 19:27:49,763 django.utils.autoreload INFO     /home/azamat/Рабочий стол/Django/social/soc_api/views.py changed, reloading.
2021-10-14 19:27:50,382 django.utils.autoreload INFO     Watching for file changes with StatReloader
2021-10-14 19:29:44,333 django.utils.autoreload INFO     /home/azamat/Рабочий стол/Django/social/soc_api/views.py changed, reloading.
2021-10-14 19:29:44,742 django.utils.autoreload INFO     Watching for file changes with StatReloader
2021-10-14 19:30:08,691 django.utils.autoreload INFO     /home/azamat/Рабочий стол/Django/social/soc_api/urls.py changed, reloading.
2021-10-14 19:30:09,075 django.utils.autoreload INFO     Watching for file changes with StatReloader
2021-10-14 19:30:21,591 django.request ERROR    Internal Server Error: /api/v1/show_posts/
Traceback (most recent call last):
  File "/home/azamat/.var/app/com.jetbrains.PyCharm-Community/data/python/lib/python3.9/site-packages/django/core/handlers/exception.py", line 47, in inner
    response = get_response(request)
  File "/home/azamat/.var/app/com.jetbrains.PyCharm-Community/data/python/lib/python3.9/site-packages/django/core/handlers/base.py", line 181, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/home/azamat/Рабочий стол/Django/social/soc_api/views.py", line 120, in show_all_news
    return render(request, 'soc_api/index.html', posts=posts)
TypeError: render() got an unexpected keyword argument 'posts'
2021-10-14 19:31:16,029 django.utils.autoreload INFO     /home/azamat/Рабочий стол/Django/social/soc_api/views.py changed, reloading.
2021-10-14 19:31:16,444 django.utils.autoreload INFO     Watching for file changes with StatReloader
2021-10-14 19:34:00,518 django.utils.autoreload INFO     /home/azamat/Рабочий стол/Django/social/soc_api/views.py changed, reloading.
2021-10-14 19:34:00,904 django.utils.autoreload INFO     Watching for file changes with StatReloader
2021-10-14 19:35:20,091 django.utils.autoreload INFO     /home/azamat/Рабочий стол/Django/social/soc_api/views.py changed, reloading.
2021-10-14 19:35:20,438 django.utils.autoreload INFO     Watching for file changes with StatReloader
2021-10-14 19:37:39,455 django.utils.autoreload INFO     /home/azamat/Рабочий стол/Django/social/soc_api/views.py changed, reloading.
2021-10-14 19:37:39,938 django.utils.autoreload INFO     Watching for file changes with StatReloader
2021-10-14 19:37:44,247 django.request WARNING  Not Found: /favicon.ico
2021-10-14 19:38:09,005 django.utils.autoreload INFO     /home/azamat/Рабочий стол/Django/social/soc_api/views.py changed, reloading.
2021-10-14 19:38:09,460 django.utils.autoreload INFO     Watching for file changes with StatReloader
2021-10-14 19:38:11,381 django.request ERROR    Internal Server Error: /api/v1/show_posts/
Traceback (most recent call last):
  File "/home/azamat/.var/app/com.jetbrains.PyCharm-Community/data/python/lib/python3.9/site-packages/django/core/handlers/exception.py", line 47, in inner
    response = get_response(request)
  File "/home/azamat/.var/app/com.jetbrains.PyCharm-Community/data/python/lib/python3.9/site-packages/django/core/handlers/base.py", line 181, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/home/azamat/Рабочий стол/Django/social/soc_api/views.py", line 123, in show_all_news
    print("Кол во записей в бд: " + str(len(posts)) + "\n" + "Время выполнения запроса: " + str(round(time_after - time_before), 3))
TypeError: str() argument 2 must be str, not int
2021-10-14 19:38:21,219 django.utils.autoreload INFO     /home/azamat/Рабочий стол/Django/social/soc_api/views.py changed, reloading.
2021-10-14 19:38:21,617 django.utils.autoreload INFO     Watching for file changes with StatReloader
2021-10-14 19:41:12,690 django.utils.autoreload INFO     /home/azamat/Рабочий стол/Django/social/soc_api/views.py changed, reloading.
2021-10-14 19:41:13,084 django.utils.autoreload INFO     Watching for file changes with StatReloader
2021-10-14 19:41:52,364 django.utils.autoreload INFO     /home/azamat/Рабочий стол/Django/social/soc_api/views.py changed, reloading.
2021-10-14 19:41:52,945 django.utils.autoreload INFO     Watching for file changes with StatReloader
2021-10-14 19:42:34,779 django.utils.autoreload INFO     /home/azamat/Рабочий стол/Django/social/soc_api/views.py changed, reloading.
2021-10-14 19:42:35,241 django.utils.autoreload INFO     Watching for file changes with StatReloader
2021-10-14 19:51:11,497 django.utils.autoreload INFO     /home/azamat/Рабочий стол/Django/social/soc_api/views.py changed, reloading.
2021-10-14 19:51:11,857 django.utils.autoreload INFO     Watching for file changes with StatReloader
2021-10-14 19:51:41,744 django.utils.autoreload INFO     /home/azamat/Рабочий стол/Django/social/soc_api/urls.py changed, reloading.
2021-10-14 19:51:42,106 django.utils.autoreload INFO     Watching for file changes with StatReloader
2021-10-14 19:51:48,723 django.request WARNING  Not Found: /api/v1/
2021-10-14 19:51:57,642 django.request WARNING  Bad Request: /api/v1/news/
2021-10-14 19:55:45,112 django.request WARNING  Bad Request: /api/v1/posts/
2021-10-14 19:56:17,344 django.request WARNING  Not Found: /favicon.ico
2021-10-14 21:40:13,679 django.utils.autoreload INFO     Watching for file changes with StatReloader
2021-10-14 21:40:16,451 django.request WARNING  Not Found: /favicon.ico
2021-10-14 21:43:03,043 django.utils.autoreload INFO     /home/azamat/Рабочий стол/Django/social/soc_api/views.py changed, reloading.
2021-10-14 21:43:03,458 django.utils.autoreload INFO     Watching for file changes with StatReloader
2021-10-14 21:43:19,125 django.utils.autoreload INFO     /home/azamat/Рабочий стол/Django/social/soc_api/views.py changed, reloading.
2021-10-14 21:43:19,471 django.utils.autoreload INFO     Watching for file changes with StatReloader
2021-10-14 21:44:27,452 django.request WARNING  Bad Request: /api/v1/posts/
2021-10-14 21:44:56,030 django.request WARNING  Forbidden: /api/v1/posts/
2021-10-14 21:50:35,273 soc.views    INFO     Post values: {'title': 'ewd', 'text': 'wddwd', 'image': None, 'user_id': 1}
2021-10-14 21:50:35,280 soc.service.content_service INFO     Пост  5|ewd был добавлен пользователем 1|Azamatik
2021-10-14 21:53:00,296 django.security.csrf WARNING  Forbidden (CSRF cookie not set.): /accounts/login/
2021-10-14 21:54:17,784 django.security.csrf WARNING  Forbidden (CSRF cookie not set.): /accounts/login/
2021-10-14 22:09:16,725 django.utils.autoreload INFO     /home/azamat/Рабочий стол/Django/social/soc_api/views.py changed, reloading.
2021-10-14 22:09:17,084 django.utils.autoreload INFO     Watching for file changes with StatReloader
2021-10-14 22:09:59,295 django.utils.autoreload INFO     /home/azamat/Рабочий стол/Django/social/soc_api/urls.py changed, reloading.
2021-10-14 22:09:59,678 django.utils.autoreload INFO     Watching for file changes with StatReloader
2021-10-14 22:10:12,440 django.request WARNING  Not Found: /api/v1/posts/10
2021-10-14 22:10:18,045 django.request WARNING  Not Found: /api/v1/posts/1
2021-10-14 22:10:20,978 django.request WARNING  Forbidden: /api/v1/posts/
2021-10-14 22:13:06,032 django.utils.autoreload INFO     /home/azamat/Рабочий стол/Django/social/soc_api/views.py changed, reloading.
2021-10-14 22:13:06,611 django.utils.autoreload INFO     Watching for file changes with StatReloader
2021-10-14 22:13:57,051 django.utils.autoreload INFO     /home/azamat/Рабочий стол/Django/social/soc_api/urls.py changed, reloading.
2021-10-14 22:13:57,644 django.utils.autoreload INFO     Watching for file changes with StatReloader
2021-10-14 22:15:09,648 django.utils.autoreload INFO     /home/azamat/Рабочий стол/Django/social/soc_api/views.py changed, reloading.
2021-10-14 22:15:10,034 django.utils.autoreload INFO     Watching for file changes with StatReloader
2021-10-14 22:16:57,544 django.utils.autoreload INFO     /home/azamat/Рабочий стол/Django/social/soc_api/views.py changed, reloading.
2021-10-14 22:16:57,907 django.utils.autoreload INFO     Watching for file changes with StatReloader
2021-10-14 22:17:26,111 django.request WARNING  Forbidden: /api/v1/users/
2021-10-14 22:22:23,294 django.utils.autoreload INFO     /home/azamat/Рабочий стол/Django/social/soc_api/views.py changed, reloading.
2021-10-14 22:22:23,729 django.utils.autoreload INFO     Watching for file changes with StatReloader
2021-10-14 22:24:28,939 django.utils.autoreload INFO     Watching for file changes with StatReloader
2021-10-14 22:26:18,790 django.utils.autoreload INFO     /home/azamat/Рабочий стол/Django/social/soc_api/views.py changed, reloading.
2021-10-14 22:26:19,327 django.utils.autoreload INFO     Watching for file changes with StatReloader
2021-10-14 22:28:46,832 django.utils.autoreload INFO     /home/azamat/Рабочий стол/Django/social/social/settings.py changed, reloading.
2021-10-14 22:28:47,238 django.utils.autoreload INFO     Watching for file changes with StatReloader
2021-10-14 22:29:09,376 django.utils.autoreload INFO     Watching for file changes with StatReloader
2021-10-14 22:29:23,042 django.request WARNING  Not Found: /favicon.ico
2021-10-14 22:35:42,464 django.utils.autoreload INFO     /home/azamat/Рабочий стол/Django/social/social/settings.py changed, reloading.
2021-10-14 22:35:43,023 django.utils.autoreload INFO     Watching for file changes with StatReloader
2021-10-14 22:37:01,053 django.utils.autoreload INFO     /home/azamat/Рабочий стол/Django/social/soc_api/views.py changed, reloading.
2021-10-14 22:37:01,492 django.utils.autoreload INFO     Watching for file changes with StatReloader
2021-10-14 22:37:26,367 django.utils.autoreload INFO     /home/azamat/Рабочий стол/Django/social/soc_api/views.py changed, reloading.
2021-10-14 22:37:26,756 django.utils.autoreload INFO     Watching for file changes with StatReloader
2021-10-14 22:37:34,598 django.request WARNING  Forbidden: /api/v1/posts/
2021-10-14 22:37:39,742 django.request WARNING  Forbidden: /api/v1/posts/
2021-10-14 22:38:27,953 django.request WARNING  Forbidden: /api/v1/posts/
2021-10-14 22:38:37,536 django.request WARNING  Forbidden: /api/v1/posts/
2021-10-14 22:39:51,605 django.request WARNING  Forbidden: /api/v1/posts/
2021-10-14 22:40:29,962 django.utils.autoreload INFO     /home/azamat/Рабочий стол/Django/social/soc_api/views.py changed, reloading.
2021-10-14 22:40:30,315 django.utils.autoreload INFO     Watching for file changes with StatReloader
2021-10-14 22:40:34,298 django.request WARNING  Forbidden: /api/v1/posts/
2021-10-14 22:40:46,030 django.request WARNING  Forbidden: /api/v1/posts/
2021-10-14 22:40:55,563 django.request WARNING  Forbidden: /api/v1/posts/
2021-10-14 22:40:59,805 django.request WARNING  Forbidden: /api/v1/posts/
2021-10-14 22:41:34,670 django.request WARNING  Forbidden: /api/v1/posts/
2021-10-16 07:33:53,448 django.utils.autoreload INFO     Watching for file changes with StatReloader
2021-10-16 07:34:09,921 django.request WARNING  Forbidden: /api/v1/posts/
2021-10-16 07:34:55,047 django.request WARNING  Not Found: /favicon.ico
2021-10-16 07:35:48,482 django.request WARNING  Forbidden: /api/v1/posts/
2021-10-16 07:38:30,323 django.utils.autoreload INFO     /home/azamat/Рабочий стол/Django/social/soc_api/views.py changed, reloading.
2021-10-16 07:38:30,684 django.utils.autoreload INFO     Watching for file changes with StatReloader
2021-10-16 07:38:55,167 django.request WARNING  Forbidden: /api/v1/posts/
2021-10-16 07:39:26,167 django.request WARNING  Forbidden: /api/v1/posts/
2021-10-16 07:39:58,793 django.utils.autoreload INFO     /home/azamat/Рабочий стол/Django/social/soc_api/views.py changed, reloading.
2021-10-16 07:39:59,140 django.utils.autoreload INFO     Watching for file changes with StatReloader
2021-10-16 07:40:43,186 django.request WARNING  Forbidden: /api/v1/posts/
2021-10-16 07:41:02,365 django.request WARNING  Forbidden: /api/v1/posts/
2021-10-16 07:42:03,431 django.request WARNING  Forbidden: /api/v1/posts/
2021-10-16 07:43:59,009 django.request WARNING  Forbidden: /api/v1/posts/
2021-10-16 07:44:45,063 django.request WARNING  Forbidden: /api/v1/posts/
2021-10-16 07:46:35,717 django.request WARNING  Forbidden: /api/v1/posts/
2021-10-16 07:46:58,660 django.request WARNING  Forbidden: /api/v1/posts/
2021-10-16 07:47:32,058 django.utils.autoreload INFO     /home/azamat/Рабочий стол/Django/social/social/settings.py changed, reloading.
2021-10-16 07:47:32,404 django.utils.autoreload INFO     Watching for file changes with StatReloader
2021-10-16 07:47:37,828 django.request WARNING  Forbidden: /api/v1/posts/
2021-10-16 15:28:43,327 django.utils.autoreload INFO     Watching for file changes with StatReloader
2021-10-16 15:28:55,597 django.request WARNING  Not Found: /favicon.ico
2021-10-16 15:31:25,857 soc_api.views INFO     Headers of requests are
{'SHELL': '/bin/sh', 'SESSION_MANAGER': 'local/azamat-Lenovo-IdeaPad-S145-15IIL:@/tmp/.ICE-unix/1092,unix/azamat-Lenovo-IdeaPad-S145-15IIL:/tmp/.ICE-unix/1092', 'QT_ACCESSIBILITY': '1', 'XDG_CONFIG_DIRS': '/app/etc/xdg:/etc/xdg', 'XDG_SESSION_PATH': '/org/freedesktop/DisplayManager/Session0', 'GNOME_DESKTOP_SESSION_ID': 'this-is-deprecated', 'PYCHARM_JDK': '${FLATPAK_DEST}/pycharm/jre64/', 'TERMINAL_EMULATOR': 'JetBrains-JediTerm', 'LANGUAGE': 'ru', 'MANDATORY_PATH': '/usr/share/gconf/cinnamon.mandatory.path', 'SSH_AUTH_SOCK': '/run/user/1000/keyring/ssh', 'XDG_DATA_HOME': '/home/azamat/.var/app/com.jetbrains.PyCharm-Community/data', 'CINNAMON_VERSION': '5.0.5', 'XDG_CONFIG_HOME': '/home/azamat/.var/app/com.jetbrains.PyCharm-Community/config', 'TERM_SESSION_ID': 'be4f76dd-950d-43c4-99db-ab2a055ae8c4', '__INTELLIJ_COMMAND_HISTFILE__': '/home/azamat/.var/app/com.jetbrains.PyCharm-Community/cache/JetBrains/PyCharmCE2021.2/terminal/history/social-history1', 'DESKTOP_SESSION': 'cinnamon', 'SSH_AGENT_PID': '1162', 'FLATPAK_ID': 'com.jetbrains.PyCharm-Community', 'GTK_MODULES': 'gail:atk-bridge', 'XDG_SEAT': 'seat0', 'PWD': '/home/azamat/Рабочий стол/Django/social', 'ALSA_CONFIG_PATH': '/usr/share/alsa/alsa-flatpak.conf', 'XDG_SESSION_DESKTOP': 'cinnamon', 'LOGNAME': 'azamat', 'QT_QPA_PLATFORMTHEME': 'qt5ct', 'XDG_SESSION_TYPE': 'x11', 'FLATPAK_JETBRAINS_ENV': '1', 'GPG_AGENT_INFO': '/run/user/1000/gnupg/S.gpg-agent:0:1', '_': '/usr/bin/python3', 'XAUTHORITY': '/run/user/1000/Xauthority', 'XDG_GREETER_DATA_DIR': '/var/lib/lightdm-data/azamat', 'GJS_DEBUG_TOPICS': 'JS ERROR;JS LOG', 'GDM_LANG': 'ru', 'GI_TYPELIB_PATH': '/app/lib/girepository-1.0', 'HOME': '/home/azamat', 'LANG': 'ru_RU.UTF-8', 'CARGO_HOME': '/home/azamat/.var/app/com.jetbrains.PyCharm-Community/data/cargo', 'XDG_CURRENT_DESKTOP': 'X-Cinnamon', 'AT_SPI_BUS_ADDRESS': 'unix:path=/run/user/1000/at-spi-bus', 'TMPDIR': '/run/user/1000/app/com.jetbrains.PyCharm-Community', 'XDG_SEAT_PATH': '/org/freedesktop/DisplayManager/Seat0', 'PULSE_CLIENTCONFIG': '/run/user/1000/pulse/config', 'XDG_CACHE_HOME': '/home/azamat/.var/app/com.jetbrains.PyCharm-Community/cache', 'GJS_DEBUG_OUTPUT': 'stderr', 'XDG_SESSION_CLASS': 'user', 'PYTHONPATH': '/app/packages/python', 'TERM': 'xterm-256color', 'GTK_OVERLAY_SCROLLING': '1', 'DEFAULTS_PATH': '/usr/share/gconf/cinnamon.default.path', 'USER': 'azamat', 'CARGO_INSTALL_ROOT': '/home/azamat/.var/app/com.jetbrains.PyCharm-Community/data/cargo', 'NPM_CONFIG_USERCONFIG': '/home/azamat/.var/app/com.jetbrains.PyCharm-Community/config/npmrc', 'DISPLAY': ':99.0', 'SHLVL': '2', 'FLATPAK_SANDBOX_DIR': '/home/azamat/.var/app/com.jetbrains.PyCharm-Community/sandbox', 'XDG_VTNR': '7', 'XDG_SESSION_ID': 'c2', 'XDG_RUNTIME_DIR': '/run/user/1000', 'GST_PLUGIN_SYSTEM_PATH': '/app/lib/gstreamer-1.0:/usr/lib/extensions/gstreamer-1.0:/usr/lib/x86_64-linux-gnu/gstreamer-1.0', 'GTK3_MODULES': 'xapp-gtk3-module', 'XDG_DATA_DIRS': '/app/share:/usr/share:/usr/share/runtime/share:/run/host/user-share:/run/host/share', 'PATH': '/app/bin:/usr/bin:/app/extensions/bin:/app/packages/bin:/home/azamat/.var/app/com.jetbrains.PyCharm-Community/data/node/bin:/home/azamat/.var/app/com.jetbrains.PyCharm-Community/data/cargo/bin:/home/azamat/.var/app/com.jetbrains.PyCharm-Community/data/python/bin', 'GDMSESSION': 'cinnamon', 'PYTHONUSERBASE': '/home/azamat/.var/app/com.jetbrains.PyCharm-Community/data/python', 'DBUS_SESSION_BUS_ADDRESS': 'unix:path=/run/user/1000/bus', 'ALSA_CONFIG_DIR': '/usr/share/alsa', 'PULSE_SERVER': 'unix:/run/user/1000/pulse/native', 'GIO_LAUNCHED_DESKTOP_FILE_PID': '1905', 'GIO_LAUNCHED_DESKTOP_FILE': '/var/lib/flatpak/exports/share/applications/com.jetbrains.PyCharm-Community.desktop', 'DJANGO_SETTINGS_MODULE': 'social.settings', 'TZ': 'Europe/Moscow', 'RUN_MAIN': 'true', 'SERVER_NAME': 'localhost', 'GATEWAY_INTERFACE': 'CGI/1.1', 'SERVER_PORT': '8000', 'REMOTE_HOST': '', 'CONTENT_LENGTH': '', 'SCRIPT_NAME': '', 'SERVER_PROTOCOL': 'HTTP/1.1', 'SERVER_SOFTWARE': 'WSGIServer/0.2', 'REQUEST_METHOD': 'GET', 'PATH_INFO': '/api/v1/posts/', 'QUERY_STRING': '', 'REMOTE_ADDR': '127.0.0.1', 'CONTENT_TYPE': 'text/plain', 'HTTP_AUTHORIZATION': 'Api-Key bcmgHFTj.kOuZKfWigP7SUkS4zKYk0FLju3U717fF', 'HTTP_USER_AGENT': 'PostmanRuntime/7.28.4', 'HTTP_ACCEPT': '*/*', 'HTTP_POSTMAN_TOKEN': '40cb3788-d7a3-4116-8cd5-0d3296a32f4c', 'HTTP_HOST': '127.0.0.1:8000', 'HTTP_ACCEPT_ENCODING': 'gzip, deflate, br', 'HTTP_CONNECTION': 'keep-alive', 'wsgi.input': <django.core.handlers.wsgi.LimitedStream object at 0x7f7c58305670>, 'wsgi.errors': <_io.TextIOWrapper name='<stderr>' mode='w' encoding='utf-8'>, 'wsgi.version': (1, 0), 'wsgi.run_once': False, 'wsgi.url_scheme': 'http', 'wsgi.multithread': True, 'wsgi.multiprocess': False, 'wsgi.file_wrapper': <class 'wsgiref.util.FileWrapper'>}
2021-10-16 18:40:51,298 django.utils.autoreload INFO     Watching for file changes with StatReloader
2021-10-16 18:40:57,377 django.request WARNING  Not Found: /admin/rest_framework_api_key/apikey/
2021-10-16 18:40:57,419 django.request WARNING  Not Found: /favicon.ico
2021-10-16 18:42:26,641 django.utils.autoreload INFO     /home/azamat/Рабочий стол/Django/social/soc_api/views.py changed, reloading.
2021-10-16 18:42:26,998 django.utils.autoreload INFO     Watching for file changes with StatReloader
2021-10-16 18:44:05,909 django.utils.autoreload INFO     /home/azamat/Рабочий стол/Django/social/soc_api/views.py changed, reloading.
2021-10-16 18:44:06,412 django.utils.autoreload INFO     Watching for file changes with StatReloader
2021-10-16 18:44:56,526 django.request WARNING  Not Found: /favicon.ico
2021-10-16 18:45:15,074 django.request WARNING  Forbidden: /api/v1/posts/
2021-10-16 18:45:32,394 django.utils.autoreload INFO     /home/azamat/Рабочий стол/Django/social/soc_api/views.py changed, reloading.
2021-10-16 18:45:32,747 django.utils.autoreload INFO     Watching for file changes with StatReloader
2021-10-16 18:45:43,479 django.request WARNING  Forbidden: /api/v1/posts/
2021-10-16 18:47:11,733 django.utils.autoreload INFO     /home/azamat/Рабочий стол/Django/social/soc_api/views.py changed, reloading.
2021-10-16 18:47:12,230 django.utils.autoreload INFO     Watching for file changes with StatReloader
2021-10-16 18:47:37,175 django.request WARNING  Forbidden: /api/v1/posts/
2021-10-16 18:47:37,470 django.request WARNING  Forbidden: /api/v1/posts/
2021-10-16 18:48:28,954 django.utils.autoreload INFO     /home/azamat/Рабочий стол/Django/social/social/settings.py changed, reloading.
2021-10-16 18:48:29,326 django.utils.autoreload INFO     Watching for file changes with StatReloader
2021-10-16 18:48:32,203 soc_api.views INFO     Headers of requests are
{'SHELL': '/bin/sh', 'SESSION_MANAGER': 'local/azamat-Lenovo-IdeaPad-S145-15IIL:@/tmp/.ICE-unix/1101,unix/azamat-Lenovo-IdeaPad-S145-15IIL:/tmp/.ICE-unix/1101', 'QT_ACCESSIBILITY': '1', 'XDG_CONFIG_DIRS': '/app/etc/xdg:/etc/xdg', 'XDG_SESSION_PATH': '/org/freedesktop/DisplayManager/Session0', 'GNOME_DESKTOP_SESSION_ID': 'this-is-deprecated', 'PYCHARM_JDK': '${FLATPAK_DEST}/pycharm/jre64/', 'TERMINAL_EMULATOR': 'JetBrains-JediTerm', 'LANGUAGE': 'ru', 'MANDATORY_PATH': '/usr/share/gconf/cinnamon.mandatory.path', 'SSH_AUTH_SOCK': '/run/user/1000/keyring/ssh', 'XDG_DATA_HOME': '/home/azamat/.var/app/com.jetbrains.PyCharm-Community/data', 'CINNAMON_VERSION': '5.0.5', 'XDG_CONFIG_HOME': '/home/azamat/.var/app/com.jetbrains.PyCharm-Community/config', 'TERM_SESSION_ID': 'b66ac1d5-bb87-4397-9e21-90e210d9bedb', '__INTELLIJ_COMMAND_HISTFILE__': '/home/azamat/.var/app/com.jetbrains.PyCharm-Community/cache/JetBrains/PyCharmCE2021.2/terminal/history/social-history', 'DESKTOP_SESSION': 'cinnamon', 'SSH_AGENT_PID': '1171', 'FLATPAK_ID': 'com.jetbrains.PyCharm-Community', 'GTK_MODULES': 'gail:atk-bridge', 'XDG_SEAT': 'seat0', 'PWD': '/home/azamat/Рабочий стол/Django/social', 'ALSA_CONFIG_PATH': '/usr/share/alsa/alsa-flatpak.conf', 'XDG_SESSION_DESKTOP': 'cinnamon', 'LOGNAME': 'azamat', 'QT_QPA_PLATFORMTHEME': 'qt5ct', 'XDG_SESSION_TYPE': 'x11', 'FLATPAK_JETBRAINS_ENV': '1', 'GPG_AGENT_INFO': '/run/user/1000/gnupg/S.gpg-agent:0:1', 'XAUTHORITY': '/run/user/1000/Xauthority', 'XDG_GREETER_DATA_DIR': '/var/lib/lightdm-data/azamat', 'GJS_DEBUG_TOPICS': 'JS ERROR;JS LOG', 'GDM_LANG': 'ru', 'GI_TYPELIB_PATH': '/app/lib/girepository-1.0', 'HOME': '/home/azamat', 'LANG': 'ru_RU.UTF-8', 'CARGO_HOME': '/home/azamat/.var/app/com.jetbrains.PyCharm-Community/data/cargo', 'XDG_CURRENT_DESKTOP': 'X-Cinnamon', 'AT_SPI_BUS_ADDRESS': 'unix:path=/run/user/1000/at-spi-bus', 'TMPDIR': '/run/user/1000/app/com.jetbrains.PyCharm-Community', 'XDG_SEAT_PATH': '/org/freedesktop/DisplayManager/Seat0', 'PULSE_CLIENTCONFIG': '/run/user/1000/pulse/config', 'XDG_CACHE_HOME': '/home/azamat/.var/app/com.jetbrains.PyCharm-Community/cache', 'GJS_DEBUG_OUTPUT': 'stderr', 'XDG_SESSION_CLASS': 'user', 'PYTHONPATH': '/app/packages/python', 'TERM': 'xterm-256color', 'GTK_OVERLAY_SCROLLING': '1', 'DEFAULTS_PATH': '/usr/share/gconf/cinnamon.default.path', 'USER': 'azamat', 'CARGO_INSTALL_ROOT': '/home/azamat/.var/app/com.jetbrains.PyCharm-Community/data/cargo', 'NPM_CONFIG_USERCONFIG': '/home/azamat/.var/app/com.jetbrains.PyCharm-Community/config/npmrc', 'DISPLAY': ':99.0', 'SHLVL': '2', 'FLATPAK_SANDBOX_DIR': '/home/azamat/.var/app/com.jetbrains.PyCharm-Community/sandbox', 'XDG_VTNR': '7', 'XDG_SESSION_ID': 'c2', 'XDG_RUNTIME_DIR': '/run/user/1000', 'GST_PLUGIN_SYSTEM_PATH': '/app/lib/gstreamer-1.0:/usr/lib/extensions/gstreamer-1.0:/usr/lib/x86_64-linux-gnu/gstreamer-1.0', 'GTK3_MODULES': 'xapp-gtk3-module', 'XDG_DATA_DIRS': '/app/share:/usr/share:/usr/share/runtime/share:/run/host/user-share:/run/host/share', 'PATH': '/app/bin:/usr/bin:/app/extensions/bin:/app/packages/bin:/home/azamat/.var/app/com.jetbrains.PyCharm-Community/data/node/bin:/home/azamat/.var/app/com.jetbrains.PyCharm-Community/data/cargo/bin:/home/azamat/.var/app/com.jetbrains.PyCharm-Community/data/python/bin', 'GDMSESSION': 'cinnamon', 'PYTHONUSERBASE': '/home/azamat/.var/app/com.jetbrains.PyCharm-Community/data/python', 'DBUS_SESSION_BUS_ADDRESS': 'unix:path=/run/user/1000/bus', 'ALSA_CONFIG_DIR': '/usr/share/alsa', 'PULSE_SERVER': 'unix:/run/user/1000/pulse/native', 'GIO_LAUNCHED_DESKTOP_FILE_PID': '2633', 'GIO_LAUNCHED_DESKTOP_FILE': '/var/lib/flatpak/exports/share/applications/com.jetbrains.PyCharm-Community.desktop', '_': '/usr/bin/python3', 'DJANGO_SETTINGS_MODULE': 'social.settings', 'TZ': 'Europe/Moscow', 'RUN_MAIN': 'true', 'SERVER_NAME': 'localhost', 'GATEWAY_INTERFACE': 'CGI/1.1', 'SERVER_PORT': '8000', 'REMOTE_HOST': '', 'CONTENT_LENGTH': '', 'SCRIPT_NAME': '', 'SERVER_PROTOCOL': 'HTTP/1.1', 'SERVER_SOFTWARE': 'WSGIServer/0.2', 'REQUEST_METHOD': 'GET', 'PATH_INFO': '/api/v1/posts/', 'QUERY_STRING': '', 'REMOTE_ADDR': '127.0.0.1', 'CONTENT_TYPE': 'text/plain', 'HTTP_AUTHORIZATION': 'Token 1bfdfa4e4a541d3909e221930311d60c308238cb', 'HTTP_USER_AGENT': 'PostmanRuntime/7.28.4', 'HTTP_ACCEPT': '*/*', 'HTTP_POSTMAN_TOKEN': '4ca46915-7542-4536-9f0e-640efb8a74cb', 'HTTP_HOST': '127.0.0.1:8000', 'HTTP_ACCEPT_ENCODING': 'gzip, deflate, br', 'HTTP_CONNECTION': 'keep-alive', 'wsgi.input': <django.core.handlers.wsgi.LimitedStream object at 0x7fe31a7e0a90>, 'wsgi.errors': <_io.TextIOWrapper name='<stderr>' mode='w' encoding='utf-8'>, 'wsgi.version': (1, 0), 'wsgi.run_once': False, 'wsgi.url_scheme': 'http', 'wsgi.multithread': True, 'wsgi.multiprocess': False, 'wsgi.file_wrapper': <class 'wsgiref.util.FileWrapper'>}
2021-10-16 18:49:20,644 django.utils.autoreload INFO     /home/azamat/Рабочий стол/Django/social/soc_api/views.py changed, reloading.
2021-10-16 18:49:21,096 django.utils.autoreload INFO     Watching for file changes with StatReloader
2021-10-16 18:49:27,012 django.request WARNING  Unauthorized: /api/v1/posts/
2021-10-16 18:49:39,936 django.request WARNING  Unauthorized: /api/v1/posts/
2021-10-16 18:51:02,952 django.request WARNING  Unauthorized: /api/v1/users/
